export const COMPLIANCE_GATE_ABI = [
  {
    type: "function",
    name: "currentRoot",
    stateMutability: "view",
    inputs: [],
    outputs: [{ type: "uint256" }],
  },
  {
    type: "function",
    name: "knownRoot",
    stateMutability: "view",
    inputs: [{ type: "uint256" }],
    outputs: [{ type: "bool" }],
  },
  {
    type: "function",
    name: "registeredToken",
    stateMutability: "view",
    inputs: [{ type: "address" }],
    outputs: [{ type: "bool" }],
  },
  {
    type: "function",
    name: "isAdmitted",
    stateMutability: "view",
    inputs: [
      { name: "token", type: "address" },
      { name: "holder", type: "address" },
    ],
    outputs: [{ type: "bool" }],
  },
  {
    type: "function",
    name: "updateRoot",
    stateMutability: "nonpayable",
    inputs: [{ name: "newRoot", type: "uint256" }],
    outputs: [],
  },
  {
    type: "function",
    name: "registerToken",
    stateMutability: "nonpayable",
    inputs: [{ name: "token", type: "address" }],
    outputs: [],
  },
  {
    type: "function",
    name: "admit",
    stateMutability: "nonpayable",
    inputs: [
      { name: "token", type: "address" },
      { name: "root", type: "uint256" },
      { name: "depth", type: "uint256" },
      { name: "nullifier", type: "uint256" },
      { name: "points", type: "uint256[8]" },
    ],
    outputs: [],
  },
  {
    type: "event",
    name: "Admitted",
    inputs: [
      { name: "token", type: "address", indexed: true },
      { name: "holder", type: "address", indexed: true },
      { name: "nullifier", type: "uint256", indexed: false },
    ],
  },
  { type: "error", name: "NotIssuer", inputs: [] },
  { type: "error", name: "UnknownRoot", inputs: [] },
  { type: "error", name: "NullifierReused", inputs: [] },
  { type: "error", name: "InvalidProof", inputs: [] },
  { type: "error", name: "TokenNotRegistered", inputs: [] },
  { type: "error", name: "DepthOutOfRange", inputs: [] },
] as const;

export const PRIVATE_RWA_ABI = [
  {
    type: "function",
    name: "name",
    stateMutability: "view",
    inputs: [],
    outputs: [{ type: "string" }],
  },
  {
    type: "function",
    name: "symbol",
    stateMutability: "view",
    inputs: [],
    outputs: [{ type: "string" }],
  },
  {
    type: "function",
    name: "decimals",
    stateMutability: "view",
    inputs: [],
    outputs: [{ type: "uint8" }],
  },
  {
    type: "function",
    name: "balanceOf",
    stateMutability: "view",
    inputs: [{ type: "address" }],
    outputs: [{ type: "uint256" }],
  },
  {
    type: "function",
    name: "totalSupply",
    stateMutability: "view",
    inputs: [],
    outputs: [{ type: "uint256" }],
  },
  {
    type: "function",
    name: "transfer",
    stateMutability: "nonpayable",
    inputs: [
      { type: "address", name: "to" },
      { type: "uint256", name: "value" },
    ],
    outputs: [{ type: "bool" }],
  },
  {
    type: "function",
    name: "mint",
    stateMutability: "nonpayable",
    inputs: [
      { type: "address", name: "to" },
      { type: "uint256", name: "amount" },
    ],
    outputs: [],
  },
  { type: "error", name: "NotAdmitted", inputs: [{ type: "address", name: "who" }] },
  { type: "error", name: "NotIssuer", inputs: [] },
] as const;
